# Common Labels
labels:
  app: "adv-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "adv-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "adv_services_schema"
    image:
      repository: "adv-services-db"

# Container Configs
image:
  repository: "adv-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/adv-services/health"
  readinessProbePath: "/adv-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx384m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
notification-sms-enabled: ""
employee-allowed-search-params: ""
citizen-allowed-search-params: ""

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_HOST_V2
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-adv-services
  - name: PERSISTER_SAVE_ADV_TOPIC
    value: save-advertisement-booking
  - name: PERSISTER_UPDATE_ADV_TOPIC
    value: update-advertisement-booking
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_IDGEN_ADVERTISEMENT_BOOKING_FORMAT
    value: {{ index .Values "egov-idgen-advertisement-booking-format" | quote }}        
  - name: NOTIFICATION_SMS_ENABLED
    value: {{ index .Values "notification-sms-enabled" | quote }}
  - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
    value: "true"
  {{- if index .Values "employee-allowed-search-params" }}
  - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "employee-allowed-search-params" | quote }}
  {{- end }}
  {{- if index .Values "citizen-allowed-search-params" }}
  - name: CITIZEN_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "citizen-allowed-search-params" | quote }}
  {{- end }}
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USR_EVENTS_CREATE_TOPIC
    value: "persist-user-events-async"
  - name: EGOV_USR_EVENTS_PAY_LINK
    value: "citizen/withoutAuth?redirectTo=egov-common/pay?consumerCode=$consumerCode&tenantId=$tenantId&businessService=$businessService"
  - name: EGOV_USR_EVENTS_PAY_CODE
    value: "PAY"          
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
