# Common Labels
labels:
  app: "egov-esign"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-esign"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: false
    schemaTable: "egov_esign_schema"
    image:
      repository: "egov-esign-db"

# Container Configs
image:
  repository: "egov-esign"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/egov-esign/health"
  readinessProbePath: "/egov-esign/health"
  livenessProbeInitialDelay: 30
  readinessProbeInitialDelay: 20
  periodSeconds: 10
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx510m -Xms510m"
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Additional Container Envs
env: |
  - name: ESIGN_RESPONSE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore-url
  - name: ESIGN_ASP_ID
    value: "PMID-001"
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: FILESTORE_BASE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: ESIGN_PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: esign-secret
        key: esign.private.key.filename   
