apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  namespace: egov
data:
  REDMINE_DB_URL: "postgresql://{{ .Values.env.REDMINE_DB_USERNAME }}:{{ .Values.env.REDMINE_DB_PASSWORD }}@{{ .Values.env.REDMINE_DB_POSTGRES }}:{{ .Values.env.REDMINE_DB_PORT }}/{{ .Values.env.REDMINE_DB_DATABASE }}"
