apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.pv.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClass }}
  awsElasticBlockStore:
    volumeID: {{ .Values.pv.awsVolumeID }}
    fsType: {{ .Values.pv.fsType }}
