# Common Labels
labels:
  app: "asset-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "asset-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "asset_services_schema"
    image:
      repository: "asset-services-db"

# Container Configs
image:
  repository: "asset-services"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/asset-services/health"
  readinessProbePath: "/asset-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
notification-sms-enabled: ""
employee-allowed-search-params: ""
citizen-allowed-search-params: ""

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-v2
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: ASSET_CALCULATOR_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: asset-calculator
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization    
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: asset-services
  - name: PERSISTER_SAVE_ASSETDETAILS_TOPIC
    value: save-asset-assetdetails
  - name: PERSISTER_UPDATE_ASSETDETAILS_TOPIC
    value: update-asset-assetdetails
  - name: PERSISTER_SAVE_ASSETASSIGNMENTDETAILS_TOPIC
    value: save-asset-assignmentdetails
  - name: PERSISTER_UPDATE_ASSETASSIGNMENTDETAILS_TOPIC
    value: update-asset-assignmentdetails
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: ASSESSMENT_WORKFLOW_ENABLED
    value: "false"
  - name: EGOV_IDGEN_ACK_FORMAT
    value: {{ index .Values "egov-idgen-ack-format" | quote }}
  - name: EGOV_IDGEN_MUTATION_FORMAT
    value: {{ index .Values "egov-idgen-mutation-format" | quote }} 
  - name: EGOV_IDGEN_ASSM_FORMAT
    value: {{ index .Values "egov-idgen-assm-format" | quote }} 
  - name: EGOV_IDGEN_PTID_FORMAT
    value: {{ index .Values "egov-idgen-ptid-format" | quote }}
  - name: NOTIFICATION_SMS_ENABLED
    value: {{ index .Values "notification-sms-enabled" | quote }}
  - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
    value: "true"
  {{- if index .Values "employee-allowed-search-params" }}
  - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "employee-allowed-search-params" | quote }}
  {{- end }}
  {{- if index .Values "citizen-allowed-search-params" }}
  - name: CITIZEN_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "citizen-allowed-search-params" | quote }}
  {{- end }}
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USR_EVENTS_CREATE_TOPIC
    value: "persist-user-events-async"
  - name: EGOV_USR_EVENTS_PAY_LINK
    value: "citizen/withoutAuth?redirectTo=egov-common/pay?consumerCode=$consumerCode&tenantId=$tenantId&businessService=$businessService"
  - name: EGOV_USR_EVENTS_PAY_CODE
    value: "PAY"          
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
