
# Common Labels
labels:
  app: "egov-property-rate-search"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-property-rate"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: false
    schemaTable: "egov_property_rate_search_schema"
    image:
      repository: "egov-property-rate-search-db"

# Container Configs
image:
  repository: "egov-property-rate-search"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/egov-property-rate-search/health"
  readinessProbePath: "/egov-property-rate-search/health"
  livenessProbeInitialDelay: 30
  readinessProbeInitialDelay: 20
  periodSeconds: 10
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx2000m -Xms2000m"
resources:
  requests:
    cpu: "500m"
    memory: "2000Mi"
  limits:
    cpu: "1"
    memory: "2Gi"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_USER_HOST
     valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    value: org.postgresql.Driver
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: DB_PORT
    value: "5432"

