# Common Labels
labels:
  app: "egov-survey-services"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-survey-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: false
    schemaTable: "egov_survey_schema"
    image:
      repository: "egov-survey-services-db"

# Container Configs
image:
  repository: "egov-survey-services"
replicas: "2"
healthChecks:
  enabled: true
  livenessProbePath: "/user/health"
  readinessProbePath: "/user/health"
appType: "java-spring"
tracing-enabled: true
egov-state-level-tenant-id: "pb"
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "egov-survey-services"
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer  
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
