# Common Labels
labels:
  app: "search-api"
  group: "web"
# Ingress Configs
ingress:
  enabled: true
#  zuul: true
  context: "search-api"

# Init Containers Configs
#initContainers:
#  dbMigration:
#    enabled: false
#    schemaTable: "egov_esign_schema"
#    image:
#      repository: "egov-esign-db"

# Container Configs
image:
  repository: "search-api"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/search-api/health"
  readinessProbePath: "/search-api/health"
  livenessProbeInitialDelay: 30
  readinessProbeInitialDelay: 20
  periodSeconds: 10
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx510m -Xms510m"
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Additional Container Envs
env: |
  - name: SERVER_CONTEXTPATH
    value: /search-api
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: DB_SV_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dbsv
        key: password
  - name: DB_SV_USER
    valueFrom:
      secretKeyRef:
        name: dbsv
        key: username
  - name: SERVER_PORT
    value: "8080"
#  - name: JAVA_OPTS
#    value: {{ index .Values "heap" | quote }}
#  - name: SECURITY_BASIC_ENABLED
#    value: "false"
#  - name: MANAGEMENT_SECURITY_ENABLED
#    value: "false"
#  - name: FILESTORE_BASE_URL
#    valueFrom:
#      configMapKeyRef:
#        name: egov-service-host

#        key: egov-filestore
