# Common Labels
labels:
  app: "chb-services"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "chb-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "chb_services_schema"
    image:
      repository: "chb-services-db"

# Container Configs
image:
  repository: "chb-services"
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/chb-services/health"
  readinessProbePath: "/chb-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
notification-sms-enabled: ""
employee-allowed-search-params: ""
citizen-allowed-search-params: ""

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-location
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  #- name: EGOV_CALCULATION_HOST
  #  valueFrom:
  #    configMapKeyRef:
  #      name: egov-service-host
  #      key: pt-calculator-v2
  #- name: EGOV_PT-SERVICES-V2_HOST
  # valueFrom:
  #    configMapKeyRef:
  #      name: egov-service-host
  #      key: pt-services-v2      
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: DECRYPTION_ABAC_ENABLED
    value: {{ index .Values "chb-decryption-abac-enabled" | quote }}
  - name: KAFKA_TOPIC_AUDIT
    value: "enc-user-audit-data" 
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: chb-services
  - name: PERSISTER_SAVE_COMMUNITYHALL_BOOKING_TOPIC
    value: save-community-hall-booking
  - name: PERSISTER_UPDATE_COMMUNITYHALL_BOOKING_TOPIC
    value: update-community-hall-booking
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: ASSESSMENT_WORKFLOW_ENABLED
    value: "false"
  - name: EGOV_IDGEN_ACK_FORMAT
    value: {{ index .Values "egov-idgen-ack-format" | quote }}
  - name: EGOV_IDGEN_MUTATION_FORMAT
    value: {{ index .Values "egov-idgen-mutation-format" | quote }} 
  - name: EGOV_IDGEN_ASSM_FORMAT
    value: {{ index .Values "egov-idgen-assm-format" | quote }} 
  - name: EGOV_IDGEN_PTID_FORMAT
    value: {{ index .Values "egov-idgen-ptid-format" | quote }}        

  - name: NOTIFICATION_SMS_ENABLED
    value: {{ index .Values "notification-sms-enabled" | quote }}
  - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
    value: "true"
  {{- if index .Values "employee-allowed-search-params" }}
  - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "employee-allowed-search-params" | quote }}
  {{- end }}
  {{- if index .Values "citizen-allowed-search-params" }}
  - name: CITIZEN_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "citizen-allowed-search-params" | quote }}
  {{- end }}
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_USR_EVENTS_CREATE_TOPIC
    value: "persist-user-events-async"
  #- name: EGOV_USR_EVENTS_PAY_LINK
  #  value: "citizen/withoutAuth?redirectTo=egov-common/pay?consumerCode=$consumerCode&tenantId=$tenantId&businessService=$businessService"
  #- name: EGOV_USR_EVENTS_PAY_CODE
  #  value: "PAY"          
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
