{{- if $.Values.controller.persistence.enabled }}
{{- range $idx, $v := until (int $.Values.controller.replicaCount) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "data-kafka-kraft-{{ $idx }}"
  labels:
    app: data-kafka-kraft
  annotations:
    topology.kubernetes.io/zone: {{ index $.Values.controller.persistence.aws $idx "zone" }}
spec:
  capacity:
    storage: {{ $.Values.controller.persistence.dataDirSize | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "aws-ebs-storage"
  awsElasticBlockStore:
    volumeID: {{ index $.Values.controller.persistence.aws $idx "volumeId" }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-release-name-kafka-controller-{{ $idx }}"
  namespace: {{ $.Values.namespace }}
  labels:
    app: data-kafka-kraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.controller.persistence.dataDirSize | quote }}
  volumeName: "data-kafka-kraft-{{ $idx }}"
  storageClassName: "aws-ebs-storage"
{{- end }}
{{- end }}

#{{- if $.Values.controller.persistence.enabled }}
#{{- range $idx, $v := until (int $.Values.controller.replicaCount) }}
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: "logs-kafka-kraft-{{ $idx }}"
#  labels:
#    app: logs-kafka-kraft
#  annotations:
#    topology.kubernetes.io/zone: {{ index $.Values.controller.persistence.aws $idx "zone" }}
#spec:
#  capacity:
#    storage: {{ $.Values.controller.persistence.dataDirSize | quote }}
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: "aws-ebs-storage"
#  awsElasticBlockStore:
#    volumeID: {{ index $.Values.controller.persistence.aws $idx "volumeId" }}
#    fsType: ext4
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: "logs-release-name-kafka-controller-{{ $idx }}"
#  namespace: {{ $.Values.namespace }}
# labels:
#    app: logs-kafka-kraft
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: {{ $.Values.controller.persistence.dataDirSize | quote }}
#  volumeName: "logs-kafka-kraft-{{ $idx }}"
#  storageClassName: "aws-ebs-storage"
#{{- end }}
#{{- end }}
