# Default values for egov-edcr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: egov

# Common Labels
labels:
  app: "egov-edcr"

# Container Configs
image:
  repository: "egov-edcr"
  pullPolicy: IfNotPresent
  tag: latest
replicas: "1"
httpPort: 8080

resources: |
  limits:
    memory: "4Gi"
  requests:
    memory: "4Gi"
min-pool-connection: "5"
max-pool-connection: "5"
env: |
  - name: DB_URL
    valueFrom: 
      configMapKeyRef: 
        name: egov-config
        key: bpa-db-url
  - name: DB_USERNAME
    valueFrom: 
      secretKeyRef: 
        name: dbedcr
        key: username
  - name: DB_PASSWORD
    valueFrom: 
      secretKeyRef: 
        name: dbedcr
        key: password
  - name: NO_TXN_DB_URL
    valueFrom: 
      configMapKeyRef: 
        name: egov-config
        key: bpa-db-url   
  - name: NO_TXN_DB_USER
    valueFrom: 
      secretKeyRef: 
        name: dbedcr
        key: username
  - name: NO_TXN_DB_PASSWORD 
    valueFrom: 
      secretKeyRef: 
        name: dbedcr
        key: password
  - name: min-pool-size
    value: {{ index .Values "min-pool-connection" | quote }}
  - name: max-pool-size
    value: {{ index .Values "max-pool-connection" | quote }}
  - name: IS_ENVIRONMENT_CENTRAL_INSTANCE
    value: "true"
  - name: STATE_TENANTID_INDEX_POSITION
    value: "0"
  - name: STATE_LEVEL_TENANTID_LENGTH
    value: "1"
  - name: IS_SUBTENANT_SCHEMA_BASED
    value: "true"
healthChecks:
  enabled: true
  livenessProbePath: "/"
  readinessProbePath: "/"

extraVolumeMounts: |
  - mountPath: /opt/jboss/wildfly/modules/system/layers/base/org/egov/settings/main/config/egov-erp-override.properties
    name: edcr-override-config
    subPath: egov-erp-override.properties 
extraVolumes: |
  - name: edcr-override-config
    configMap:
      name: egov-edcr-config        


scheduler: false
dev_mode: false
jpa_showSql: false
master_server: true
sms: true
mail: true
captcha: low
redis_host: redis.backbone 
redis_port: 6379
statewide_migration: true
state_migration: true
state_schema: state
multitenancy: true
db_flyway: false

mail_config: |
  mail.port=465
  mail.host=smtp.gmail.com
  mail.sender.username=${mail-sender-username}
  mail.sender.password=${mail-sender-password}
  mail.smtps.auth=true
  mail.smtps.starttls.enable=true
  mail.smtps.debug=false

smc_config: |
  sms.priority.enabled=false
  sms.provider.url=http://api.smscountry.com/SMSCwebservice_bulk.aspx
  sms.sender.username=${sms-username}
  sms.sender.password=${sms-password}
  sms.sender=SMSCOUNTRY
  sms.sender.req.param.name=sid
  sms.sender.username.req.param.name=User
  sms.sender.password.req.param.name=passwd
  sms.destination.mobile.req.param.name=mobilenumber
  sms.message.req.param.name=message
  sms.extra.req.params=mtype=N&DR=Y
  sms.error.codes=401,403,404,405,406,407,408,409,410,411,412,413,414      
  
elastic_config: |
  #elasticsearch.hosts=elasticsearch-client-v1.es-cluster
  #elasticsearch.port=9200
  #elasticsearch.cluster.name=elasticsearch-v1
  elasticsearch.enable=false
  
elastic_search_config: |
  elasticsearch.enable=false
  search.index.q=java:/jms/queue/searchindex
  #search.hosts=elasticsearch-client-v1.es-cluster
  #search.port=9200
  #search.clusterName=elasticsearch-v1

aadhaar_config: |
  aadhaar.wsdl.url=http://164.100.132.193:8010/SRDHAadhaarInfoServices/services/SRDHAadhaarInfoservices?wsdl
  aadhaar.info.ws.method=getAadhaarInfo
  aadhaar.info.ws.namespace=http://srdhuidinfoservices/ecentric/com/xsd
  aadhaar.info.ws.client.impl.class.fqn=org.egov.infra.aadhaar.webservice.contract.AadhaarInfoImpl

tenants: |
  common.domain.name=egov-micro-dev.egovernments.org
  #tenant.egov-dcr-mercury.egovernments.org=mercury
  #tenant.egov-dcr-jupiter.egovernments.org=jupiter
  tenant.egov-micro-dev.egovernments.org=state
  client.id=punjab
  #tenant.bihar-micro-dev.egovernments.org=state
  #tenant.biharsharif.bihar-micro-dev.egovernments.org=biharsharif
  #tenant.muzaffarpur.bihar-micro-dev.egovernments.org=muzaffarpur
  #tenant.danapur.bihar-micro-dev.egovernments.org=danapur
  #tenant.hajipur.bihar-micro-dev.egovernments.org=hajipur
  #tenant.sitamarhi.bihar-micro-dev.egovernments.org=sitamarhi
  #tenant.katihar.bihar-micro-dev.egovernments.org=katihar
  #tenant.bhagalpur.bihar-micro-dev.egovernments.org=bhagalpur
  #tenant.sonpur.bihar-micro-dev.egovernments.org=sonpur 
  tenant.amritsar-egov-micro-dev.egovernments.org=amritsar
  tenant.testing-egov-micro-dev.egovernments.org=testing
  tenant.jalandhar-egov-micro-dev.egovernments.org=jalandhar
  #location.user.role=Collection Operator
  collection.debitaccounthead.client.impl.class=org.egov.collection.integration.services.DebitAccountHeadDetailsServiceImpl

microservice: |
  ms.url=http://egov-filestore.egov:8080/
  filestoreservice.beanname=egovMicroServiceStore
  mdms.enable=true
  mdms.host=http://egov-mdms-service.egov:8080/
  mdms.searchurl=egov-mdms-service/v1/_search

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  waf: 
    enabled: false
  additionalAnnotations: |
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
  context: "egi"
  

