# Common Labels
labels:
  app: "ndc-services"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "ndc-services"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: ture
    schemaTable: "ndc-services_schema"
    image:
      repository: "ndc-services-db"

# Container Configs
image:
  repository: "ndc-services"
replicas: "2"
healthChecks:
  enabled: true
  livenessProbePath: "/ndc-services/health"
  readinessProbePath: "/ndc-services/health"
appType: "java-spring"
tracing-enabled: true
egov-state-level-tenant-id: "pb"
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_NDCCALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ndc-calculator
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: WORKFLOW_CONTEXT_PATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2    
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "ndc-services"
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer  
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
